swagger: '2.0'

# Metadata
info:
  title: Discovery APIs MCC/MNC
  version: 1.0.0
  description: |
        Documentation of GSMA Discovery APIs

host: discover.mobileconnect.io
schemes:
- https

# API Paths
paths:
  /{org_name}/v2/discovery:
    get:
      operationId: MCC-MNC-DISCOVERY-GET
      summary: Fetching Operator Detail from MCC / MNC Discovery
      description: |
        **Valid Responses**

        Below will be the response for valid request

        | Scenario             | Parameters           | Status Code              | Description                 |
        |----------------------|----------------------|--------------------------|-----------------------------|
        | With MCC/MNC Pair                  | Identified-MCC, Identified-MNC, Redirect_URL                  | 200 | If Mcc/Mnc is valid and if the Accept header is 'application/json'. The cookies are set based on 'Remember Me' selection in the UI. If Enum-Nonce cookie is reset, as this is not a MSISDN based discovery. |
        | With MCC/MNC Pair, Ignore-Cookies  | Identified-MCC, Identified-MNC, Redirect_URL, Ignore-Cookies  | 200 | The request is redirected back to the same URL with Most-Recent-Selected-Operator & Most-Recent-Selected-Operator-Expiry cookies rest. If the redirect is followed then discovery would be attempted |
        | With MCC/MNC Pair, Set-Cookies     | Identified-MCC, Identified-MNC, Redirect_URL, Set-Cookies     | 200 |  The response does not set any cookies. And all cookies were anyway reset in the previous response |
        | With MCC/MNC Pair, Manually-Select | Identified-MCC, Identified-MNC, Redirect_URL, Manually-Select | 202 | Response is a redirect to the operator selection web page, where the user can either select an operator or or submit his/her MSISDN. Make sure to URL encode the parameters, when needed. The submitted request will look like below |
        | With out MCC/MNC Pair              | Redirect_URL | 202 | Get the operator selection web page |

        **Error Responses**

        Below will be the error scenario for invalid request

        | Scenario             | Status               | Error                    | Description                 |
        |----------------------|----------------------|--------------------------|-----------------------------|
        | Missing Redirect_URL         | 400 Bad Request | Invalid_Request     | Redirect_URL missing |
        | Missing Identified-MNC       | 400 Bad Request | Invalid_Request     | The Mnc value is not specified in this discovery request |
        | Missing Identified-MCC       | 400 Bad Request | Invalid_Request     | The Mcc value is not specified in this discovery request |
        | Missing Authorization Header | 401 Unauthorized | Unauthorized_Access | Your request needs a valid session or valid credentials |
        | Wrong MCC/MNC Pair           | 404 Not Found | Not_Found_Entity    | There is no organization with the specified mcc/mnc pair |
      produces:
      - application/json
      parameters:
        - name: org_name
          in: path
          description: Serving Operator (MNO) Organization  name as created in the Exchange
          required: true
          type: string
        - name: Accept
          in: header
          description: Content-Types that are acceptable for the response.
          required: true
          type: string
          default: application/json
          enum:
            - application/json
            - application/xml
        - name: Identified-MCC
          in: query
          description: Identified Mobile Country Codes for request
          required: true
          type: integer
        - name: Identified-MNC
          in: query
          description: Identified Mobile Network Codes for request
          required: true
          type: integer
        - name: Redirect_URL
          in: query
          description: Redirect URL of Application
          required: true
          type: string
        - name: Ignore-Cookies
          in: query
          description: Ignore(true/false) Cookies for request
          type: boolean
        - name: Set-Cookies
          in: query
          description: Set(true/false) Cookies for request
          type: boolean
        - name: Manually-Select
          in: query
          description: Set Cookies true/false
          type: boolean
      security:
      - BasicAuth: []
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/MNC_MCC_Discovery_Resp"
        202:
          description: Accepted
          schema:
            $ref: "#/definitions/MNC_MCC_Discovery_OpSelection_Resp"
        400:
          description: Bad Request (Missing any of Redirect_URL, Identified-MNC, Identified-MCC)
          schema:
            $ref: "#/definitions/DiscoveryError400"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/DiscoveryError401"

    post:
      operationId: MCC-MNC-DISCOVERY-POST
      summary: Posting Operator Detail from MCC / MNC Discovery
      description: |
        **Valid Responses**

        Below will be the response for valid request

        | Scenario              | Parameters           | Status Code           | Description                 |
        |-----------------------|----------------------|-----------------------|-----------------------------|
        | With MCC/MNC Pair     | Identified-MCC, Identified-MNC, Redirect_URL | 200 | If Mcc/Mnc is valid and if the Accept header is 'application/json'. The cookies are set based on 'Remember Me' selection in the UI. If Enum-Nonce cookie is reset, as this is not a MSISDN based discovery. |
        | With out MCC/MNC Pair | Redirect_URL                                 | 202 | Get the operator selection web page |

        **Error Responses**

        Below will be the error scenario for invalid request

        | Scenario             | Status               | Error                    | Description                 |
        |----------------------|----------------------|--------------------------|-----------------------------|
        | Missing Redirect_URL         | 400 Bad Request | Invalid_Request     | Redirect_URL missing |
        | Missing Identified-MNC       | 400 Bad Request | Invalid_Request     | The Mnc value is not specified in this discovery request |
        | Missing Identified-MCC       | 400 Bad Request | Invalid_Request     | The Mcc value is not specified in this discovery request |
        | Missing Authorization Header | 401 Unauthorized | Unauthorized_Access | Your request needs a valid session or valid credentials |
        | Wrong MCC/MNC Pair           | 404 Not Found | Not_Found_Entity    | There is no organization with the specified mcc/mnc pair |
      produces:
      - application/json
      parameters:
        - name: org_name
          in: path
          description: Serving Operator (MNO) Organization  Name
          required: true
          type: string
        - name: Accept
          in: header
          description: Content-Types that are acceptable for the response.
          required: true
          type: string
          default: application/json
          enum:
            - application/json
            - application/xml
        - name: Content-Type
          in: header
          description: Content-Types that are acceptable for the response.
          type: string
          default: x-www-form-urlencoded
          enum:
            - x-www-form-urlencoded
        - name: body
          in: body
          description: Request Body
          required: true
          schema:
            type: object
            properties:
              Identified-MCC:
                type: integer
                format: int64
                description: Identified Mobile Country Code
                example: 214
              Identified-MNC:
                type: integer
                format: int64
                description: Identified Mobile Network Codes
                example: 01
              Redirect_URL:
                type: string
                description: Redirect_URL of application
                example: http://apigee.com
      security:
      - BasicAuth: []
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/MNC_MCC_Discovery_Resp"
        202:
          description: Accepted
          schema:
            $ref: "#/definitions/MNC_MCC_Discovery_OpSelection_Resp"
        400:
          description: Bad Request (Missing any of Redirect_URL, Identified-MNC, Identified-MCC)
          schema:
            $ref: "#/definitions/DiscoveryError400"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/DiscoveryError401"

# Security Definitions
securityDefinitions:
  BasicAuth:
    type: basic

# Definitions
definitions:
  MNC_MCC_Discovery_Resp:
    type: object
    properties:
      ttl:
        type: integer
        format: int64
        description: Time To Live of data in a computer or network in miliseconds
        example: 1498963352
      response:
        type: object
        properties:
          client_id:
            type: string
            description: ID Gateway client_id as returned in the Exchange-Discovery API for a valid operator
            example: X-c******
          client_secret:
            type: string
            description: ID Gateway client_secret as returned in the Exchange-Discovery API for a valid operator
            example: X-Br******
          serving_operator:
            type: string
            description: Serving Operator as created in the Exchange
            example: vodafone_spain
          country:
            type: string
            description: Country of Serving Operator
            example: Spain
          currency:
            type: string
            description: Currency of Serving Operator Country
            example: EUR
          client_name:
            type: string
            description: Client Name of Serving Operator
            example: apigee_test_3
          apis:
            type: object
            description: List of Operator APIs
            properties:
              operatorid:
                type: object
                properties:
                  link:
                    type: array
                    description: Array of Operator API Links
                    items:
                      $ref: "#/definitions/OperatorLinks"

  MNC_MCC_Discovery_OpSelection_Resp:
    type: object
    properties:
      links:
        type: array
        description: Array of Operator API Links
        items:
          $ref: "#/definitions/OperatorLink"

  OperatorLinks:
    type: object
    properties:
      href:
        type: string
        description: Method API url for operator selection UI flow with session id
        example: https://idp.mobileconnect.gemalto.com/idp/vodafonespain/oidc/mc/authorize
      rel:
        type: string
        description: Method Name like authorization,token,userinfo,tokenrevoke,premiuminfo etc
        example: authorization

  OperatorLink:
    type: object
    properties:
      href:
        type: string
        description: Method API url for operator selection UI flow with session id
        example: https://exchange-i-test.dn.apigee.net/apigee_monitor/v2/discovery/operator-selection?session_id=U7GXhTcpDAiLNJPpst6B4ai1rclnlVYe5h23UQMX6DweaRdEew&ext_session_id=3qb0qnoIqXz4mCFbiYsCMgmcRLytBhZVCDB51zpUPdg1PIAVx561pb0Yavusucb6Aa88T3YUhEipljhwpnnVggs6kNx5qOv0s1XcG6%2FPCxarmE%2Bs9qbl
      rel:
        type: string
        description: Method Name like operatorSelection
        example: operatorSelection

  DiscoveryError400:
    type: object
    properties:
      error:
        type: string
        description: "'Invalid_Request' for Missing Redirect_URL, Missing Identified-MNC, Missing Identified-MCC scenarios | 'Unauthorized_Access' for Missing Authorization Header scenario | 'Not_Found_Entity' for Wrong MCC/MNC Pair scenario"
        example: Invalid_Request
      description:
        type: string
        example: Redirect_URL missing
        description: "'Redirect_URL missing' for Missing Redirect_URL, 'The Mnc value is not specified in this discovery request' for Missing Identified-MNC, 'The Mcc value is not specified in this discovery request' for Missing Identified-MCC scenarios | 'Redirect_URL missing' for Missing Redirect_URL scenario | 'Your request needs a valid session or valid credentials' for Missing Authorization Header scenario | 'There is no organization with the specified mcc/mnc pair' for Wrong MCC/MNC Pair scenario"

  DiscoveryError401:
    type: object
    properties:
      error:
        type: string
        description: "'Invalid_Request' for Missing Redirect_URL, Missing Identified-MNC, Missing Identified-MCC scenarios | 'Unauthorized_Access' for Missing Authorization Header scenario | 'Not_Found_Entity' for Wrong MCC/MNC Pair scenario"
        example: Unauthorized_Access
      description:
        type: string
        example: Your request needs a valid session or valid credentials
        description: "'Redirect_URL missing' for Missing Redirect_URL, 'The Mnc value is not specified in this discovery request' for Missing Identified-MNC, 'The Mcc value is not specified in this discovery request' for Missing Identified-MCC scenarios | 'Redirect_URL missing' for Missing Redirect_URL scenario | 'Your request needs a valid session or valid credentials' for Missing Authorization Header scenario | 'There is no organization with the specified mcc/mnc pair' for Wrong MCC/MNC Pair scenario"
