swagger: '2.0'

# Metadata
info:
  title: Discovery APIs IP
  version: 1.0.0
  description: |
        Documentation of GSMA Discovery APIs
host: discover.mobileconnect.io
schemes:
- https

# API Paths
paths:
  /{org_name}/v2/discovery:
    get:
      operationId: IP-DISCOVERY-GET
      summary: Fetching Operator Detail from IP Discovery
      description: |
        A discovery request is made by the application 'X-Using-Mobile-Data: true' header.
        
        **Valid Responses**

        | Scenario                 | Parameters                    | Status Code | Description                 |
        |--------------------------|-------------------------------|-------------|-----------------------------|
        | With X-Source-IP         | Local-Client-IP, Redirect_URL | 200 | Provides Operator Details |
        | With invalid X-Source-IP | Redirect_URL                  | 202 | Get the operator selection web page |

        **Error Responses**

        | Scenario                     | Status           | Error               | Description                 |
        |------------------------------|------------------|---------------------|-----------------------------|
        | Missing Redirect_URL         | 400 Bad Request  | Invalid_Request     | Redirect_URL missing |
        | Missing Authorization Header | 401 Unauthorised | Unauthorized_Access | Your request needs a valid session or valid credentials |
      produces:
      - application/json
      parameters:
        - name: org_name
          in: path
          description: Serving Organization ID as created in the Exchange
          required: true
          type: string
        - name: Accept
          in: header
          description: Content-Types that are acceptable for the response.
          required: true
          type: string
          default: application/json
          enum:
            - application/json
            - application/xml
        - name: X-Using-Mobile-Data
          in: header
          description: X-Using-Mobile-Data boolean value
          required: true
          type: boolean
        - name: X-Source-IP
          in: header
          description: X-Source-IP Address
          required: true
          type: string
        - name: Redirect_URL
          in: query
          description: Redirect URL of application
          required: true
          type: string
      security:
      - BasicAuth: []
      responses:
        200:
          description: Accepted
          schema:
            $ref: "#/definitions/IP_Discovery_OpSelection_Resp"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/DiscoveryError"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/DiscoveryError"

# Security Definitions
securityDefinitions:
  BasicAuth:
    type: basic

# Definitions
definitions:
  IP_Discovery_OpSelection_Resp:
    type: object
    properties:
      links:
        type: array
        description: Array of Operator API Links
        items:
          $ref: "#/definitions/OperatorLink"

  OperatorLink:
    type: object
    properties:
      rel:
        type: string
        description: Method Name 
        example: operatorSelection
      href:
        type: string
        description: Method API url
        example: https://exchange-i-test.dn.apigee.net/apigee_monitor/v2/discovery/operator-selection?session_id=U7GXhTcpDAiLNJPpst6B4ai1rclnlVYe5h23UQMX6DweaRdEew&ext_session_id=3qb0qnoIqXz4mCFbiYsCMgmcRLytBhZVCDB51zpUPdg1PIAVx561pb0Yavusucb6Aa88T3YUhEipljhwpnnVggs6kNx5qOv0s1XcG6%2FPCxarmE%2Bs9qbl

  DiscoveryError:
    type: object
    properties:
      error:
        type: string
        description: Invalid_Request for Missing Redirect_URL scenario | "Unauthorized_Access" for Missing Authorization Header scenario
        example: Invalid_Request
      description:
        type: string
        description: Redirect_URL missing for Missing Redirect_URL scenario | "Your request needs a valid session or valid credentials" for Missing Authorization Header scenario
        example: Redirect_URL missing
