swagger: '2.0'

# Metadata
info:
  title: Discovery APIs MCC/MNC
  version: 1.0.0
  description: |
        Documentation of GSMA Discovery APIs
host: discover.mobileconnect.io
schemes:
- https

# API Paths
paths:
  /{org_name}/v2/discovery:
    get:
      operationId: MCC-MNC-DISCOVERY-GET
      summary:  MCC / MNC Discovery
      description: |
        Fetching Operator Detail from MCC / MNC Discovery
      produces:
      - application/json
      parameters:
        - name: org_name
          in: path
          description: Organization Name
          required: true
          type: string
        - name: Accept
          in: header
          description: Accept Type
          required: true
          type: string
          default: application/json
          enum:
            - application/json
            - application/xml
        - name: Identified-MCC
          in: query
          description: Identified MCC
          required: true
          type: integer
        - name: Identified-MNC
          in: query
          description: Identified MNC
          required: true
          type: integer
        - name: Redirect_URL
          in: query
          description: Redirect URL
          required: true
          type: string
        - name: Ignore-Cookies
          in: query
          description: Ignore Cookies true/false
          type: boolean
        - name: Set-Cookies
          in: query
          description: Set Cookies true/false
          type: boolean
        - name: Manually-Select
          in: query
          description: Set Cookies true/false
          type: boolean
      security:
      - BasicAuth: []
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/MNC_MCC_Discovery_Resp"
        202:
          description: Accepted
          schema:
            $ref: "#/definitions/MNC_MCC_Discovery_OpSelection_Resp"
        400:
          description: Bad Request (Missing any of Redirect_URL, Identified-MNC, Identified-MCC)
          schema:
            $ref: "#/definitions/DiscoveryError"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/DiscoveryError"

    post:
      operationId: MCC-MNC-DISCOVERY-POST
      summary:  MCC / MNC Discovery
      description: |
       Posting Operator Detail from MCC / MNC Discovery
      produces:
      - application/json
      parameters:
        - name: org_name
          in: path
          description: Organization Name
          required: true
          type: string
        - name: Accept
          in: header
          description: Accept Type
          required: true
          type: string
          default: application/json
          enum:
            - application/json
            - application/xml
        - name: Content-Type
          in: header
          description: Content Type
          type: string
          default: x-www-form-urlencoded
          enum:
            - x-www-form-urlencoded
        - name: body
          in: body
          description: Request Body
          required: true
          schema:
            type: object
            properties:
              Identified-MCC:
                type: integer
                format: int64
              Identified-MNC:
                type: integer
                format: int64
              Redirect_URL:
                type: string
      security:
      - BasicAuth: []
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/MNC_MCC_Discovery_Resp"
        202:
          description: Accepted
          schema:
            $ref: "#/definitions/MNC_MCC_Discovery_OpSelection_Resp"
        400:
          description: Bad Request (Missing any of Redirect_URL, Identified-MNC, Identified-MCC)
          schema:
            $ref: "#/definitions/DiscoveryError"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/DiscoveryError"

# Security Definitions
securityDefinitions:
  BasicAuth:
    type: basic

# Definitions
definitions:
  MNC_MCC_Discovery_Resp:
    type: object
    properties:
      ttl:
        type: integer
        format: int64
        description: Time To Live
      response:
        type: object
        properties:
          client_id:
            type: string
            description: X-Client ID
          client_secret:
            type: string
            description: X-Client Secret
          serving_operator:
            type: string
            description: Serving Operator
          country:
            type: string
            description: Country
          currency:
            type: string
            description: Currency
          client_name:
            type: string
            description: Client Name
          apis:
            type: object
            description: List of Operator APIs
            properties:
              operatorid:
                type: object
                properties:
                  link:
                    type: array
                    description: Array of Operator API Links
                    items:
                      $ref: "#/definitions/OperatorLink"

  MNC_MCC_Discovery_OpSelection_Resp:
    type: object
    properties:
      links:
        type: array
        description: Array of Operator API Links
        items:
          $ref: "#/definitions/OperatorLink"

  OperatorLink:
    type: object
    properties:
      href:
        type: string
        description: Method API
      rel:
        type: string
        description: Method Name

  DiscoveryError:
    type: object
    properties:
      error:
        type: string
        description: Invalid_Request for Missing Redirect_URL, Missing Identified-MNC, Missing Identified-MCC scenarios | "Unauthorized_Access" for Missing Authorization Header scenario | "Not_Found_Entity" for Wrong MCC/MNC Pair scenario
      description:
        type: string
        description: Redirect_URL missing for Missing Redirect_URL, "The Mnc value is not specified in this discovery request" for Missing Identified-MNC, "The Mcc value is not specified in this discovery request" for Missing Identified-MCC scenarios | Redirect_URL missing for Missing Redirect_URL scenario | "Your request needs a valid session or valid credentials" for Missing Authorization Header scenario | "There is no organization with the specified mcc/mnc pair" for Wrong MCC/MNC Pair scenario